// Terminology mapping dictionary (spec section 5): client spreadsheet wording -> Training ID.
// This is the auto-match layer for CSV import. Anything not found here (or in master_trainings
// exact names) is queued in import_column_map as "needs_review" rather than guessed at -
// per spec section 15, similar-sounding trainings are never silently collapsed together.
//
// Stored lowercase/trimmed; matching normalizes the same way plus strips punctuation.

const TRAINING_ALIASES = [
  ['OSHA10', 'TRN-001'],
  ['OSHA 10', 'TRN-001'],
  ['OSHA-10', 'TRN-001'],
  ['OSHA30', 'TRN-002'],
  ['OSHA 30', 'TRN-002'],
  ['OSHA-30', 'TRN-002'],
  ['CPR/First Aid', 'TRN-012'],
  ['First Aid/CPR', 'TRN-012'],
  ['First Aid-CPR-AED', 'TRN-012'],
  ['First Aid CPR AED', 'TRN-012'],
  ['Confined Spaces', 'TRN-009'],
  ['Confined Space', 'TRN-009'],
  ['LOTO', 'TRN-010'],
  ['Lockout Tagout', 'TRN-010'],
  ['Lockout/Tagout', 'TRN-010'],
  ['Hazcom', 'TRN-005'],
  ['Hazard Communication', 'TRN-005'],
  ['Fall Protection', 'TRN-006'],
  ['Ladders', 'TRN-007'],
  ['Ladder Safety', 'TRN-007'],
  ['Trenching/Excavation', 'TRN-008'],
  ['Trenching and Excavations', 'TRN-008'],
  ['Trenching', 'TRN-008'],
  ['Scaffold', 'TRN-027'],
  ['Scaffolding', 'TRN-027'],
  ['Scaffold User', 'TRN-027'],
  ['Scaffolds', 'TRN-027'],
  ['Forklift', 'TRN-030'],
  ['Forklift Operator', 'TRN-030'],
  ['Forklift Training', 'TRN-030'],
  ['Counterbalance Forklift', 'TRN-031'],
  ['Rough Terrain Forklift', 'TRN-032'],
  ['MEWP', 'TRN-033'],
  ['Boom Lift', 'TRN-034'],
  ['Scissor Lift', 'TRN-035'],
  ['Mini Ex', 'TRN-036'],
  ['MiniEx', 'TRN-036'],
  ['Mini Excavator', 'TRN-036'],
  ['Excavator Operator', 'TRN-037'],
  ['Skid Steer', 'TRN-038'],
  ['Respiratory Protection', 'TRN-014'],
  ['Respiratory Fit Testing', 'TRN-015'],
  ['Fit Test', 'TRN-015'],
  ['Respirator Fit Test', 'TRN-015'],
  ['Qualified Rigger', 'TRN-041'],
  ['Qualified Signal', 'TRN-042'],
  ['Qualified Signalperson', 'TRN-042'],
  ['Electrical', 'TRN-019'],
  ['Electrical Safety', 'TRN-019'],
  ['Electrical Hazard', 'TRN-020'],
  ['Electrical Hazard Awareness', 'TRN-020'],
  ['Fire Safety', 'TRN-017'],
  ['Fire Prevention', 'TRN-017'],
  ['Fire Safety/Prevention', 'TRN-017'],
  ['Fire Extinguisher', 'TRN-018'],
  ['PPE', 'TRN-016'],
  ['Hand and Power Tools', 'TRN-023'],
  ['Hand & Power Tools', 'TRN-023'],
  ['Machine Guarding', 'TRN-024'],
  ['Lifting Safety', 'TRN-026'],
  ['Stored Energy', 'TRN-025'],
  ['USAP', 'TRN-043'],
  ['Utility Strike Avoidance Planning', 'TRN-043'],
  ['Demolition/Rework', 'TRN-044'],
  ['Demolition', 'TRN-044'],
  ['Crane', 'TRN-040'],
  ['Crane Safety', 'TRN-040'],
  ['Defensive Driving', 'TRN-047'],
  ['Dump Truck', 'TRN-039'],
  ['EAP', 'TRN-050'],
  ['Emergency Action Plan', 'TRN-050'],
  ['New Employee Orientation', 'TRN-051'],
  ['NHO', 'TRN-051'],
  ['New Hire Orientation', 'TRN-051'],
  ['Carbon Monoxide Exposure', 'TRN-052'],
  ['Carbon Monoxide', 'TRN-052'],
  ['Ergonomics', 'TRN-049'],
  ['Welding & Hot Work', 'TRN-045'],
  ['Welding and Hot Work', 'TRN-045'],
  ['Refueling Safety', 'TRN-046'],
  ['Heat Illness', 'TRN-021'],
  ['Heat Illness Prevention', 'TRN-021'],
  ['Silica', 'TRN-022'],
  ['Silica Awareness', 'TRN-022'],
  ['Bloodborne', 'TRN-013'],
  ['Bloodborne Pathogens', 'TRN-013'],
  ['CDL', 'TRN-048'],
  ["Commercial Driver's License", 'TRN-048'],
];

module.exports = TRAINING_ALIASES;
