// Master Training Catalog - replaced 2026-09-17 (Keeley's request) with her real, final
// pre-launch list (Master_Template_List.xlsx: ID # / Certification / Record Type / Default
// Expiration). This is a full clean-slate replacement, not a merge with anything before it.
// No category field (Keeley's request, 2026-09-17: "those aren't necessary") - the source
// never had one either.
//
// Three data-fidelity fixes from the raw source, confirmed with Keeley: TRN-021 Flagger's
// expiration was truncated to "4 yea" in the file (she confirmed: 4 Years - a new option added
// to EXPIRATION_UNITS in server/lib/statusEngine.js for this). TRN-089/TRN-090 listed "PRN" as
// their expiration - her call: treat as "None" (no fixed renewal cycle). TRN-033's name had a
// stray "&amp;" HTML entity, and TRN-074 through TRN-080 (PIT Operator classes) had a lost/
// mis-encoded character where an en dash belongs - both cleaned up here, not a Keeley judgment
// call, just fixing garbled source text.

const MASTER_TRAININGS = [
  ["TRN-001", "3M Medical Clearance for Respiratory Use", "Certification", "1 Year"],
  ["TRN-002", "AC Safety Day", "Training", "1 Year"],
  ["TRN-003", "Active Assailant Training", "Training", "None"],
  ["TRN-004", "Advanced MESH", "Training", "None"],
  ["TRN-005", "Angle Grinder Safety", "Training", "1 Year"],
  ["TRN-006", "Benzene Awareness", "Training", "1 Year"],
  ["TRN-007", "Bloodborne Pathogens", "Training", "1 Year"],
  ["TRN-008", "CCS Substance Abuse Program Card", "Certification", "1 Year"],
  ["TRN-009", "CHST", "Certification", "5 Years"],
  ["TRN-010", "CMESH", "Certification", "None"],
  ["TRN-011", "Cold Weather Safety & Winter Driving", "Training", "1 Year"],
  ["TRN-012", "Confined Space", "Training", "1 Year"],
  ["TRN-013", "Defensive Driving", "Training", "None"],
  ["TRN-014", "Electrical Safety", "Training", "1 Year"],
  ["TRN-015", "Ergonomics", "Training", "None"],
  ["TRN-016", "Fall Protection", "Training", "1 Year"],
  ["TRN-017", "Fire Extinguisher Training", "Training", "1 Year"],
  ["TRN-018", "Fire Protection", "Training", "1 Year"],
  ["TRN-019", "Firestop", "Training", "None"],
  ["TRN-020", "First Aid/CPR/AED", "Certification", "2 Years"],
  ["TRN-021", "Flagger", "Certification", "4 Years"],
  ["TRN-022", "Forklift Operator", "Certification", "3 Years"],
  ["TRN-023", "Forklift Operator Train the Trainer", "Certification", "3 Years"],
  ["TRN-024", "Gantry Crane", "Certification", "3 Years"],
  ["TRN-025", "Gantry Crane Train the Trainer", "Certification", "3 Years"],
  ["TRN-026", "Hand and Power Tools", "Training", "None"],
  ["TRN-027", "Hand Signals", "Training", "None"],
  ["TRN-028", "Hazard Communication (HAZCOM)", "Training", "1 Year"],
  ["TRN-029", "HAZWOPER", "Certification", "1 Year"],
  ["TRN-030", "Health Hazards", "Training", "None"],
  ["TRN-031", "Hearing Conservation", "Training", "1 Year"],
  ["TRN-032", "Heat Stress", "Training", "1 Year"],
  ["TRN-033", "Hot Work & Fire Watch Safety", "Training", "None"],
  ["TRN-034", "Incident Investigation & Case Management", "Training", "None"],
  ["TRN-035", "Incident Reporting", "Training", "None"],
  ["TRN-036", "Inclement Weather Conditions", "Training", "None"],
  ["TRN-037", "Introduction to Health Standard for Industrial Hygienist #125", "Training", "None"],
  ["TRN-038", "Job Safety Analysis", "Training", "None"],
  ["TRN-039", "Ladder Safety Awareness", "Training", "1 Year"],
  ["TRN-040", "Lead Awareness", "Training", "1 Year"],
  ["TRN-041", "Lifting Techniques", "Training", "None"],
  ["TRN-042", "Lockout/Tagout (LOTO)", "Training", "None"],
  ["TRN-043", "Lull Operator", "Certification", "3 Years"],
  ["TRN-044", "Lull Operator Train the Trainer", "Certification", "3 Years"],
  ["TRN-045", "Machine Guarding", "Training", "None"],
  ["TRN-046", "Material Handling", "Training", "None"],
  ["TRN-047", "Mental Health and Stress in the Workplace", "Training", "None"],
  ["TRN-048", "MESH", "Certification", "None"],
  ["TRN-049", "MEWP: Boom Lift", "Certification", "3 Years"],
  ["TRN-050", "MEWP: Scissor Lift", "Certification", "3 Years"],
  ["TRN-051", "MEWP: Train the Trainer", "Certification", "3 Years"],
  ["TRN-052", "Mini Excavator - Train the Trainer", "Certification", "None"],
  ["TRN-053", "Mini Excavator Operator", "Certification", "3 Years"],
  ["TRN-054", "Mini Track Loader Operator", "Certification", "None"],
  ["TRN-055", "N95 Voluntary Respiratory Use Form", "Certification", "None"],
  ["TRN-056", "New Hire Orientation: AC", "Training", "None"],
  ["TRN-057", "New Hire Orientation: JR's Maintenance", "Training", "None"],
  ["TRN-058", "NFPA 70E", "Certification", "None"],
  ["TRN-059", "Off-Road Powered Industrial Trucks (Specify Type)", "Certification", "None"],
  ["TRN-060", "OSHA 10 (Construction)", "Certification", "None"],
  ["TRN-061", "OSHA 10 (General Industry)", "Certification", "None"],
  ["TRN-062", "OSHA 30 (Construction)", "Certification", "None"],
  ["TRN-063", "OSHA 30 (General Industry)", "Certification", "None"],
  ["TRN-064", "OSHA 500", "Certification", "3 Years"],
  ["TRN-065", "OSHA 501", "Certification", "3 Years"],
  ["TRN-066", "OSHA 502", "Certification", "3 Years"],
  ["TRN-067", "OSHA 503", "Certification", "3 Years"],
  ["TRN-068", "OSHA 510", "Certification", "None"],
  ["TRN-069", "OSHA 511", "Certification", "None"],
  ["TRN-070", "OSHA 7500", "Certification", "None"],
  ["TRN-071", "OSHA 7505", "Certification", "None"],
  ["TRN-072", "OSHA Recordkeeping", "Training", "None"],
  ["TRN-073", "Pandemic Preparedness", "Training", "None"],
  ["TRN-074", "PIT Operator: Class I – Electric motor, sit-down or stand-up rider trucks (counterbalanced forklifts)", "Certification", "3 Years"],
  ["TRN-075", "PIT Operator: Class II – Electric motor narrow-aisle trucks (order pickers, reach trucks)", "Certification", "3 Years"],
  ["TRN-076", "PIT Operator: Class III – Electric motor hand trucks / hand-rider trucks (pallet jacks, walkie/rider stackers)", "Certification", "3 Years"],
  ["TRN-077", "PIT Operator: Class IV – Internal combustion engine trucks with solid/cushion tires (indoor warehouse use)", "Certification", "1 Year"],
  ["TRN-078", "PIT Operator: Class V – Internal combustion engine trucks with pneumatic tires (outdoor/rough surface use)", "Certification", "1 Year"],
  ["TRN-079", "PIT Operator: Class VI – Electric and internal combustion engine tractors (tow tractors)", "Certification", "3 Years"],
  ["TRN-080", "PIT Operator: Class VII – Rough terrain forklift trucks (construction/outdoor sites)", "Certification", "3 Years"],
  ["TRN-081", "PIT: Train the Trainer", "Certification", "3 Years"],
  ["TRN-082", "PPE - Personal Protective Equipment", "Training", "1 Year"],
  ["TRN-083", "Process Safety Management", "Training", "3 Years"],
  ["TRN-084", "Respiratory Fit Testing", "Training", "1 Year"],
  ["TRN-085", "Respiratory Protection", "Certification", "1 Year"],
  ["TRN-086", "Rigging", "Certification", "3 Years"],
  ["TRN-087", "Safety Inspections", "Training", "None"],
  ["TRN-088", "Scaffold Inspector", "Certification", "None"],
  ["TRN-089", "Scaffold User", "Certification", "None"],
  ["TRN-090", "Scaffolding", "Training", "None"],
  ["TRN-091", "Signal Person", "Certification", "1 Year"],
  ["TRN-092", "Silica", "Training", "1 Year"],
  ["TRN-093", "Skid Steer Operator", "Certification", "3 Years"],
  ["TRN-094", "Skid Steer Train the Trainer", "Certification", "3 Years"],
  ["TRN-095", "Spotter Safety", "Training", "1 Year"],
  ["TRN-096", "Spray Foam Insulation", "Training", "1 Year"],
  ["TRN-097", "Steel Erection", "Training", "1 Year"],
  ["TRN-098", "Struck By/Caught-In-Between", "Training", "3 Years"],
  ["TRN-099", "Trenching and Excavations", "Training", "3 Years"],
  ["TRN-100", "Trowel Machine Operator", "Certification", "3 Years"],
  ["TRN-101", "Universal Technician 40 CFR Part 82, Subpart F", "Certification", "None"],
  ["TRN-102", "Walkable Ceiling Training", "Training", "1 Year"],
  ["TRN-103", "Work Zone Safety", "Training", "1 Year"],
  // Added 2026-09-17 (Keeley's request) - post-launch additions to the catalog above.
  ["TRN-104", "Welding & Hot Work", "Training", "None"],
  ["TRN-105", "Emergency Action Plan (EAP)", "Training", "None"],
  ["TRN-106", "Refueling Safety", "Training", "None"],
  ["TRN-107", "Mast Climber", "Certification", "None"],
].map(([training_id, training_name, training_type, default_expiration], idx) => ({
  training_id,
  training_name,
  training_type,
  default_expiration,
  active: 1,
  display_order: idx + 1,
}));

module.exports = MASTER_TRAININGS;
