// Master Training Catalog - source of truth. Do not create per-client variants of this list;
// client terminology differences are handled via training_aliases + client_training_requirements.
//
// Every default_expiration is 'None' - Keeley's call: no automatic expiration rules get
// assigned to trainings, since the app is primarily tracking completion, not enforcing
// renewal cycles. Any training's default (or a client-specific override) can still be
// changed later from the Master Trainings / Client Settings admin pages; this is just the
// starting point.
//
// Replaced 2026-09-01 (Keeley's request) with a detailed 140-entry catalog built from a
// certification-by-certification review of real client data: equipment classes, MEWP lift
// types, and OSHA industry tracks are kept as distinct entries instead of collapsed into one
// generic training, and issuer/trainer-vs-operator variants are never merged together. Several
// entries are deliberately named "... - Not Specified" where the source data didn't say enough
// to pick a more specific one (e.g. which OSHA industry track, which MEWP lift type) - these are
// meant to be reviewed and reassigned to a more specific entry once that's known, not left as-is
// forever.

const MASTER_TRAININGS = [
  ["TRN-001", "(Duke DROPP..) PowerSafe Duke Dropped Object Prevention Class", "Safety", "Training", "None"],
  ["TRN-002", "AC Safety Day", "Orientation", "Orientation", "None"],
  ["TRN-003", "Active Assailant Training", "Emergency", "Training", "None"],
  ["TRN-004", "Advanced MESH", "Safety", "Certification", "None"],
  ["TRN-005", "Angle Grinder Safety", "Safety", "Training", "None"],
  ["TRN-006", "Basic Spotter", "Equipment/Safety", "Training", "None"],
  ["TRN-007", "Benzene Awareness", "Safety", "Training", "None"],
  ["TRN-008", "Bloodborne Pathogens", "Medical/Emergency", "Training", "None"],
  ["TRN-009", "Carbon Monoxide Exposure", "Safety", "Training", "None"],
  ["TRN-010", "CCS Substance Abuse Program Card", "Medical/Emergency", "Certification", "None"],
  ["TRN-011", "CHST", "Safety", "Certification", "None"],
  ["TRN-012", "CMESH", "Safety", "Certification", "None"],
  ["TRN-013", "Cold Weather Safety & Winter Driving", "Driver/Fleet", "Training", "None"],
  ["TRN-014", "Commercial Driver's License (CDL)", "Driver/Fleet", "License", "None"],
  ["TRN-015", "Confined Space", "Safety", "Training", "None"],
  ["TRN-016", "Counterbalance Forklift", "Equipment", "Certification", "None"],
  ["TRN-017", "Crane Safety (General)", "Equipment", "Certification", "None"],
  ["TRN-018", "Decision Making", "Safety", "Training", "None"],
  ["TRN-019", "Defensive Driving", "Driver/Fleet", "Training", "None"],
  ["TRN-020", "Demolition / Rework", "Safety", "Training", "None"],
  ["TRN-021", "Dump Truck", "Equipment", "Certification", "None"],
  ["TRN-022", "Electrical Hazard Awareness", "Safety", "Training", "None"],
  ["TRN-023", "Electrical Safety", "Safety", "Training", "None"],
  ["TRN-024", "Emergency Action Plan (EAP)", "Emergency", "Training", "None"],
  ["TRN-025", "Environmental Safety", "Safety", "Training", "None"],
  ["TRN-026", "Ergonomics", "Safety", "Training", "None"],
  ["TRN-027", "Excavator Operator", "Equipment", "Certification", "None"],
  ["TRN-028", "Fall Protection", "Safety", "Training", "None"],
  ["TRN-029", "Fall Protection / Falling Objects / PFAS Inspection", "Safety", "Training", "None"],
  ["TRN-030", "Fiber Optic Training", "Safety", "Training", "None"],
  ["TRN-031", "Fire Extinguisher", "Safety", "Training", "None"],
  ["TRN-032", "Fire Safety / Prevention", "Safety", "Training", "None"],
  ["TRN-033", "Firestop", "Safety", "Training", "None"],
  ["TRN-034", "First Aid / CPR / AED – Issuer Not Specified", "Medical/Emergency", "Training", "None"],
  ["TRN-035", "First Aid/CPR/AED – American Heart Association", "Medical/Emergency", "Training", "None"],
  ["TRN-036", "First Aid/CPR/AED – American Red Cross", "Medical/Emergency", "Training", "None"],
  ["TRN-037", "First Aid/CPR/AED – Instructor", "Medical/Emergency", "Certification", "None"],
  ["TRN-038", "Flagger", "Safety", "Training", "None"],
  ["TRN-039", "Focus Five", "Safety", "Training", "None"],
  ["TRN-040", "Forklift Operator – Class Not Specified", "Equipment", "Certification", "None"],
  ["TRN-041", "Forklift Operator – Trainer (Class Not Specified)", "Equipment", "Certification", "None"],
  ["TRN-042", "Gantry / Overhead Crane Operator", "Equipment", "Certification", "None"],
  ["TRN-043", "Gantry Crane – Train the Trainer", "Equipment", "Certification", "None"],
  ["TRN-044", "Hand & Power Tools", "Safety", "Training", "None"],
  ["TRN-045", "Hand Signals", "Rigging", "Certification", "None"],
  ["TRN-046", "Hazard Communication (HAZCOM)", "Safety", "Training", "None"],
  ["TRN-047", "HAZWOPER", "Safety", "Training", "None"],
  ["TRN-048", "Health Hazards", "Safety", "Training", "None"],
  ["TRN-049", "Hearing Conservation", "Safety", "Training", "None"],
  ["TRN-050", "Heat Illness Prevention", "Safety", "Training", "None"],
  ["TRN-051", "Hot Work & Fire Watch Safety", "Safety", "Training", "None"],
  ["TRN-052", "Incident Investigation", "Safety", "Training", "None"],
  ["TRN-053", "Incident Reporting", "Safety", "Training", "None"],
  ["TRN-054", "Incident Response & Case Management", "Medical/Emergency", "Training", "None"],
  ["TRN-055", "Inclement Weather Conditions", "Safety", "Training", "None"],
  ["TRN-056", "Intermediate Rigger", "Rigging", "Certification", "None"],
  ["TRN-057", "Introduction to Health Standard for Industrial Hygienist #125", "Safety", "Certification", "None"],
  ["TRN-058", "Job Safety Analysis", "Safety", "Training", "None"],
  ["TRN-059", "Ladder Safety", "Safety", "Training", "None"],
  ["TRN-060", "Ladder Safety – Monthly Safety Meeting", "Safety", "Training", "None"],
  ["TRN-061", "Lead Abatement Hazard Awareness", "Safety", "Training", "None"],
  ["TRN-062", "Lead Awareness", "Safety", "Training", "None"],
  ["TRN-063", "Lifting Safety", "Safety", "Training", "None"],
  ["TRN-064", "Lockout/Tagout (LOTO)", "Safety", "Training", "None"],
  ["TRN-065", "Lull Operator", "Equipment", "Certification", "None"],
  ["TRN-066", "Lull Operator – Trainer", "Equipment", "Certification", "None"],
  ["TRN-067", "Machine Guarding", "Safety", "Training", "None"],
  ["TRN-068", "Material Handler (Forklift/Telehandler)", "Equipment", "Certification", "None"],
  ["TRN-069", "Material Handling", "Safety", "Training", "None"],
  ["TRN-070", "Mental Health and Stress in the Workplace", "Safety", "Training", "None"],
  ["TRN-071", "MESH", "Safety", "Certification", "None"],
  ["TRN-072", "MEWP – Train the Trainer", "Equipment", "Certification", "None"],
  ["TRN-073", "MEWP Operator – Lift Type Not Specified", "Equipment", "Certification", "None"],
  ["TRN-074", "MEWP: Boom Lift Operator", "Equipment", "Certification", "None"],
  ["TRN-075", "Mini Excavator – Train the Trainer", "Equipment", "Certification", "None"],
  ["TRN-076", "Mini Excavator Operator", "Equipment", "Certification", "None"],
  ["TRN-077", "Mini Track Loader Operator", "Equipment", "Certification", "None"],
  ["TRN-078", "Mobile Scaffold", "Equipment/Safety", "Training", "None"],
  ["TRN-079", "N95 Voluntary Use Acknowledgment", "Medical/Emergency", "Training", "None"],
  ["TRN-080", "NCDOL 2023 NC Construction Forum", "Orientation", "Orientation", "None"],
  ["TRN-081", "NCDOL Collateral First Aid Requirement", "Medical/Emergency", "Training", "None"],
  ["TRN-082", "New Hire Orientation (NHO)", "Orientation", "Orientation", "None"],
  ["TRN-083", "NFPA 70E", "Safety", "Training", "None"],
  ["TRN-084", "Off-Road Powered Industrial Trucks", "Equipment", "Certification", "None"],
  ["TRN-085", "OSHA 10-Hour – Construction Industry (1926)", "OSHA", "Training", "None"],
  ["TRN-086", "OSHA 10-Hour – General Industry (1910)", "OSHA", "Training", "None"],
  ["TRN-087", "OSHA 10-Hour – Industry Not Specified", "OSHA", "Training", "None"],
  ["TRN-088", "OSHA 30-Hour – Construction Industry (1926)", "OSHA", "Training", "None"],
  ["TRN-089", "OSHA 30-Hour – General Industry (1910)", "OSHA", "Training", "None"],
  ["TRN-090", "OSHA 30-Hour – Industry Not Specified", "OSHA", "Training", "None"],
  ["TRN-091", "OSHA 500 – Trainer Course, Construction Industry", "OSHA", "Certification", "None"],
  ["TRN-092", "OSHA 501 – Trainer Course, General Industry", "OSHA", "Certification", "None"],
  ["TRN-093", "OSHA 502 – Trainer Update, Construction Industry", "OSHA", "Certification", "None"],
  ["TRN-094", "OSHA 503 – Trainer Update, General Industry", "OSHA", "Certification", "None"],
  ["TRN-095", "OSHA 510 – OSH Standards for the Construction Industry", "OSHA", "Training", "None"],
  ["TRN-096", "OSHA 511 – OSH Standards for General Industry", "OSHA", "Training", "None"],
  ["TRN-097", "OSHA 7500 – Introduction to Safety and Health Management", "OSHA", "Training", "None"],
  ["TRN-098", "OSHA 7505 – Introduction to Incident (Accident) Investigation", "OSHA", "Training", "None"],
  ["TRN-099", "OSHA Recordkeeping (300/300A)", "OSHA", "Training", "None"],
  ["TRN-100", "Pandemic Preparedness", "Emergency", "Training", "None"],
  ["TRN-101", "Personal Protective Equipment (PPE)", "Safety", "Training", "None"],
  ["TRN-102", "Powered Industrial Truck Train-the-Trainer, Classes I–VII (EPRO Safety Solutions)", "Equipment", "Certification", "None"],
  ["TRN-103", "Process Safety Management", "Safety", "Training", "None"],
  ["TRN-104", "Qualified Rigger", "Rigging", "Certification", "None"],
  ["TRN-105", "Qualified Signalperson", "Rigging", "Certification", "None"],
  ["TRN-106", "Refueling Safety", "Safety", "Training", "None"],
  ["TRN-107", "Respirator Medical Evaluation", "Medical/Emergency", "Certification", "None"],
  ["TRN-108", "Respiratory Protection", "Safety", "Training", "None"],
  ["TRN-109", "Rigging – General/Level Not Specified", "Rigging", "Certification", "None"],
  ["TRN-110", "Rough Terrain Forklift", "Equipment", "Certification", "None"],
  ["TRN-111", "Safety Inspections", "Safety", "Training", "None"],
  ["TRN-112", "Safety Meeting: Hearing Loss Prevention", "Safety", "Training", "None"],
  ["TRN-113", "Scaffold Inspector", "Equipment/Safety", "Certification", "None"],
  ["TRN-114", "Scaffold User", "Equipment/Safety", "Training", "None"],
  ["TRN-115", "Scaffolding – General/Level Not Specified", "Equipment/Safety", "Training", "None"],
  ["TRN-116", "Scissor Lift Operator", "Equipment", "Certification", "None"],
  ["TRN-117", "Silica Awareness", "Safety", "Training", "None"],
  ["TRN-118", "Silica Competent Person", "Safety", "Certification", "None"],
  ["TRN-119", "Skid Steer – Train the Trainer", "Equipment", "Certification", "None"],
  ["TRN-120", "Skid Steer Operator", "Equipment", "Certification", "None"],
  ["TRN-121", "Skid Steer Spotter", "Equipment", "Training", "None"],
  ["TRN-122", "Spotter Awareness", "Safety", "Training", "None"],
  ["TRN-123", "Spray Foam Insulation", "Safety", "Training", "None"],
  ["TRN-124", "Steel Erection", "Safety", "Training", "None"],
  ["TRN-125", "Stored Energy", "Safety", "Training", "None"],
  ["TRN-126", "Struck By/Caught-In-Between", "Safety", "Training", "None"],
  ["TRN-127", "Supported Scaffolding Competent Person", "Equipment/Safety", "Certification", "None"],
  ["TRN-128", "Suspended Scaffold", "Equipment/Safety", "Training", "None"],
  ["TRN-129", "Toolbox Talk – Mandatory vs. Voluntary Usage", "Orientation", "Orientation", "None"],
  ["TRN-130", "Trenching & Excavation", "Safety", "Training", "None"],
  ["TRN-131", "Trenching Competent Person", "Safety", "Certification", "None"],
  ["TRN-132", "Trowel Machine Operator", "Equipment", "Certification", "None"],
  ["TRN-133", "Universal Technician 40 CFR Part 82, Subpart F", "Safety", "Certification", "None"],
  ["TRN-134", "Utility Strike Avoidance Planning (USAP)", "Safety", "Training", "None"],
  ["TRN-135", "Walkable Ceiling Training", "Safety", "Training", "None"],
  ["TRN-136", "Welding & Hot Work", "Safety", "Training", "None"],
  ["TRN-137", "Work Zone Safety", "Safety", "Training", "None"],
  ["TRN-138", "Respirator Fit Test – Qualitative (QLFT)", "Safety", "Fit Test", "None"],
  ["TRN-139", "Respirator Fit Test – Quantitative (QNFT)", "Safety", "Fit Test", "None"],
  ["TRN-140", "Respirator Fit Test – Method Not Specified", "Safety", "Fit Test", "None"],
].map(([training_id, training_name, category, training_type, default_expiration], idx) => ({
  training_id,
  training_name,
  category,
  training_type,
  default_expiration,
  active: 1,
  display_order: idx + 1,
}));

module.exports = MASTER_TRAININGS;
